name: $(Major).$(Minor)$(Rev:.r)

pool:
  vmImage: 'windows-latest'

trigger:
  batch: true
  paths:
    exclude:
    - Deployment
        
variables:
- group: Versioning
- name: BuildPlatform
  value: 'Any CPU'
- name: BuildConfiguration
  value: 'NuGetRelease'

steps:
- task: PowerShell@2
  displayName: 'Set NuGet Package Version Number'
  inputs:
    filePath: 'Deployment/Scripts/SetNuGetPackageVersion.ps1'
    arguments: '-branch "$(Build.SourceBranch)" -buildNumber "$(Build.BuildNumber)"'

- template: 'Template_Build.yml'
  parameters:
    solutions: '**\\*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet'
  condition: and(succeeded(), eq(variables.CreateNuGetPackage, 'true'))
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.SourcesDirectory)\Vermaat.Crm.Specflow\Vermaat.Crm.Specflow.csproj'
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: 'byBuildNumber'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  condition: and(succeeded(), eq(variables.CreateNuGetPackage, 'true'))
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: NuGet.org

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: CI