name: $(Major).$(Minor)$(Rev:.r)
pool:
  vmImage: 'windows-latest'
variables:
- group: Versioning
- name: BuildPlatform
  value: 'Any CPU'
- name: BuildConfiguration
  value: 'NuGetRelease'

steps:
- template: 'Template_Build.yml'
  parameters:
    solutions: '**\\*.sln'